//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieManagement.dataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movy
    {
        public System.Guid id { get; set; }
        public string Title { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public int Length { get; set; }
        public string Rating { get; set; }
        public Nullable<double> AverageScore { get; set; }
        public Nullable<System.Guid> Categoryid { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Review Review { get; set; }
    }
}
