//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieManagement.dataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int Employe_ID { get; set; }
        public Nullable<System.DateTime> Salary_Month_Year { get; set; }
        public string amount { get; set; }
    }
}
